name: fusage
description: Tanks logbook and consumption calculator.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  provider: ^6.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  flutter_native_splash: ^2.2.12
  auto_size_text: ^3.0.0
  url_launcher: ^6.1.6
  file_picker: ^5.2.2
  flutter_launcher_icons: ^0.10.0
  permission_handler: ^10.2.0
  dropdown_button2: ^1.9.1
  tutorial_coach_mark: ^1.2.4
  lazy_load_scrollview: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter.ttf

flutter_native_splash:
  image: assets/logo.png
  color: "#141e30"